### ISSUE TITLE
Half the size

### ISSUE THREAD

**Issue by jimmywarting** [sindresorhus/is-docker#12]
...If i could write it the way I wanted
```js
import {statSync, readFileSync} from 'node:fs'

let isDocker,
test = fn => {
  try {
    return fn(), 1
  } catch (_) {
    return 0
  }
}

export default () => !!(isDocker ??=
  test(() => statSync('/.dockerenv')) ||
  test(() => readFileSync('/proc/self/cgroup', 'utf8').includes('docker')))
```

Certainly don't follow any popular standardjs or xo rules, but hey... just wanted to give an example if i where to update it to ESM and at the same time try to come up with some new solution
require node 15 doe (cuz of `??=`) 😞

**Comment by sindresorhus** [comment]
I prefer optimizing for readability. This package only runs on Node.js, so code golfing the size is meaningless.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/is-docker/releases/tag/v3.0.0

**Comment by jimmywarting** [comment]
code golfing is fun nonetheless :)
