### ISSUE TITLE
Detect Podman as well

### ISSUE THREAD

**Issue by RReverser** [sindresorhus/is-docker#14]
Podman is a new-ish popular daemonless alternative to Docker, which is mostly compatible, but doesn't pass the checks defined in this module.

As a result, packages like `open` that depend on this one, assume they're inside a WSL environment, end up trying to invoke PowerShell inside a container, and, of course, fail to do so: https://github.com/sindresorhus/open/blob/27e4e3a193928fe0cfb43cee746292df339bb332/index.js#L123-L128

**Comment by sindresorhus** [comment]
I think it's better to make it a new package: https://github.com/sindresorhus/is-inside-container

Will add it to `open` soon.

**Comment by RReverser** [comment]
Thanks. Should I open separate issue for tracking on the `open` repo?

**Comment by sindresorhus** [comment]
No. I will remember. Just waiting for the open PR there to be merged first.

**Comment by RReverser** [comment]
> Just waiting for the open PR there to be merged first.

Not to sound entitled, but... any chance to bypass that PR for now and do this small change first?

I installed Docker Desktop for now to work around this problem on the project I'm working on (which fails with Podman due to react-scripts -> [...] -> open -> this issue), but my machine really struggles with Docker, especially in comparison with Podman 😅

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/open/releases/tag/v8.4.2

**Comment by RReverser** [comment]
Thank you!
