### ISSUE TITLE
Library with high vulnerability

### ISSUE THREAD

**Issue by lugogregory** [sindresorhus/is-docker#16]
I am using its most updated version v-3.0.0, as a third-party dependency in my project, and performing a quality test with Kiuwan, a high vulnerability has been detected. The vulnerability error it indicates is the following:

runc through 1.0-rc6, as used in Docker before 18.09.2 and other products, allows attackers to overwrite the host runc binary (and consequently obtain host root access) by leveraging the ability to execute a command as root within one of these types of containers: (1) a new container with an attacker-controlled image, or (2) an existing container, to which the attacker previously had write access, that can be attached with docker exec. This occurs because of file-descriptor mishandling, related to /proc/self/exe.

![image](https://github.com/user-attachments/assets/aa80303b-b6e9-4502-bbbf-875b257f02c6)

**Comment by sindresorhus** [comment]
None of those vulnerabilities seem related to `is-docker`.

**Comment by lugogregory** [comment]
Hi @sindresorhus, the last vulnerability is related with is-docker-3.0.0:

"runc through 1.0-rc6, as used in Docker before 18.09.2 and other products, allows attackers to overwrite the host runc binary (and consequently obtain host root access) by leveraging the ability to execute a command as root within one of these types of containers: (1) a new container with an attacker-controlled image, or (2) an existing container, to which the attacker previously had write access, that can be attached with docker exec. This occurs because of file-descriptor mishandling, related to /proc/self/exe."

![image](https://github.com/user-attachments/assets/7e65a15e-79dd-4007-b628-0bef1a5a0848)

**Comment by sindresorhus** [comment]
That is a vulnerability in Docker, but I still don't see how it's a vulnerability in this package.
