### ISSUE TITLE
Make `isDocker()` async and add `.sync()` method

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/is-docker#2]
Do you want that? Seems more in line with other modules.

```js
isDocker().then(docker => {
    console.log(docker);
    //=> true
});

isDocker.sync();
//=> false
```

**Comment by sindresorhus** [comment]
I considered it initially, but couldn't think of a use-case for needing it asynchronously. If you have an actual use-case I'd be happy to change.

**Comment by SamVerschueren** [comment]
Nope, don't have one :). Thought it would be more consistent but I'd be fine if we wait until someone has an actual use case.

**Comment by sindresorhus** [comment]
Cool. I can leave this open for discovery.

**Comment by piranna** [comment]
Could you accept a pull-request for that? I try to use async methods when available...

By the way, I did the same trick of the `.dockerinit` file to check Docker myself, lol :-P

**Comment by sindresorhus** [comment]
@piranna Provide a use-case. Just using async methods for the sake of it is not a good argument.

**Comment by piranna** [comment]
It's not the shake of it, just try to freed the event loop as much as possible by not using blocking functions. Also async API seems to me cleaner and more elegant that using a `try-catch` block for just that same reason.

**Comment by sindresorhus** [comment]
That sounds a bit naive. You should use the right tools for the job. Sometimes synchronous functions are better suited. For example, the event loops comes with some overhead, so in some cases synchronous functions can be a lot faster, and can be used when you're making CLI apps and not a server. Also note that it only does a maximum of two `fs` calls no matter how many times you call it, as it's cached, so the impact is negligible.

Again, happy to reconsider if you provide actual use-cases.
