### ISSUE TITLE
Cannot detect a docker environment when running under latest AWS ECS Fargate

### ISSUE THREAD

**Issue by mweberxyz** [sindresorhus/is-docker#9]
When launching an ECS Fargate task with the most recent platform version, is-docker returns false.

See attached task configuration and output.

Task Configuration:
![image](https://user-images.githubusercontent.com/1062734/113194098-beab9980-922e-11eb-8b24-744f6403c8db.png)

Output:
![image](https://user-images.githubusercontent.com/1062734/113194148-ccf9b580-922e-11eb-928b-7b6d6413341a.png)

**Comment by sindresorhus** [comment]
Can you try this potential fix? https://github.com/sindresorhus/is-docker/commit/344a2928b0cb2cb346549d0d125ee5a1dd9a0171

```
npm install 'sindresorhus/is-docker#344a2928b0cb2cb346549d0d125ee5a1dd9a0171'
```

**Comment by mweberxyz** [comment]
Yes, looks like that branch correctly detects the ECS docker environment!

![image](https://user-images.githubusercontent.com/1062734/113199834-8fe4f180-9235-11eb-979e-c2918815776e.png)

![image](https://user-images.githubusercontent.com/1062734/113199888-a55a1b80-9235-11eb-9e37-1db2963abe76.png)
